name: Build
on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '11.4' }}
      XC_PROJECT: ${{ 'GreatProducts.xcodeproj' }}
      XC_SCHEME: ${{ 'GreatProducts' }}
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Build app
      run: /usr/bin/xcodebuild build -project "$XC_PROJECT" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
